# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
    configurationVersion: 0.2.0
    assertions:
        - resource: Microsoft.Windows.Developer/OsVersion
          directives:
            description: Verify at least Windows 11 22H2 installed
            allowPrerelease: true
          settings:
            MinVersion: '10.0.22621'
    resources:
        # Command Line
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: PowerShell
          directives:
            description: Install PowerShell
            allowPrerelease: false
          settings:
            id: Microsoft.PowerShell
            source: winget        
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: WSL
          directives:
            description: Install Windows Subsystem for Linux
            allowPrerelease: false
          settings:
            id: "9P9TQF7MRM4R"
            source: msstore
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          dependsOn:
            - WSL
          id: UbuntuWSL2
          directives:
            description: Install Ubuntu WSL2
            allowPrerelease: false
          settings:
            id: Canonical.Ubuntu.2204
            source: winget
        # Containers/Kubernetes
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          dependsOn:
            - WSL        
          id: DockerDesktop
          directives:
            description: Install Docker Desktop
            allowPrerelease: false
          settings:
            id: Docker.DockerDesktop
            source: winget		            
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: npm
          directives:
            description: Install NodeJS version 20
            allowPrerelease: false
          settings:
            id: OpenJS.NodeJS
            version: "16.10.0"
            source: winget
        # Azure Tools
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: AzCLI
          directives:
            description: Install Azure CLI
            allowPrerelease: false
          settings:
            id: Microsoft.AzureCLI
            source: winget        
        # Developer Tools
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: VisualStudio
          directives:
            description: Install Visual Studio 2022 Professional
            allowPrerelease: true
          settings:
            id: Microsoft.VisualStudio.2022.Professional
            source: winget
        - resource: Microsoft.VisualStudio.DSC/VSComponents
          dependsOn:
            - VisualStudio
          directives:
            description: Install required VS workloads from vsconfig file
            allowPrerelease: true
          settings:
            productId: Microsoft.VisualStudio.Product.Professional
            channelId: VisualStudio.17.Release
            vsConfigFile: '${WinGetConfigRoot}\..\.vsconfig'
            includeRecommended: true        
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: Git
          directives:
            description: Install Git
            allowPrerelease: false
          settings:
            id: Git.Git
            source: winget
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: JMeter
          directives:
            description: Install JMeter
            allowPrerelease: false
          settings:
            id: DEVCOM.JMeter
            source: winget
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: SSMS
          directives:
            description: Install SSMS
            allowPrerelease: false
          settings:
            id: Microsoft.SQLServerManagementStudio
            source: winget
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: PostgreSQL.PostgreSQL.16
          directives:
            description: Install PostgreSQL.PostgreSQL.16
            allowPrerelease: false
          settings:
            id: PostgreSQL.PostgreSQL.16
            source: winget            
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: Postman
          directives:
            description: Install Postman
            allowPrerelease: false
          settings:
            id: Postman.Postman
            source: winget
        - resource: Microsoft.WinGet.DSC/WinGetPackage
          id: VSCode
          directives:
            description: Install VSCode
            allowPrerelease: false
          settings:
            id: Microsoft.VisualStudioCode
            source: winget
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode
          directives:
            description: Install YAML Extension
            allowPrerelease: true
          settings:
            Name: redhat.vscode-yaml
            Ensure: Present
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install Amazon Q Extension
            allowPrerelease: true
          settings:
            Name: amazonwebservices.amazon-q-vscode
            Ensure: Present
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install Angular.ng-template Extension
            allowPrerelease: true
          settings:
            Name: Angular.ng-template
            Ensure: Present
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install dbaeumer.vscode-eslint Extension
            allowPrerelease: true
          settings:
            Name: dbaeumer.vscode-eslint
            Ensure: Present
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install eamodio.gitlens Extension
            allowPrerelease: true
          settings:
            Name: eamodio.gitlens
            Ensure: Present
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install ms-dotnettools.csdevkit Extension
            allowPrerelease: true
          settings:
            Name: ms-dotnettools.csdevkit
            Ensure: Present
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install ms-dotnettools.csharp Extension
            allowPrerelease: true
          settings:
            Name: ms-dotnettools.csharp
            Ensure: Present
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install ms-dotnettools.vscode-dotnet-runtime Extension
            allowPrerelease: true
          settings:
            Name: ms-dotnettools.vscode-dotnet-runtime
            Ensure: Present
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install ms-dotnettools.vscodeintellicode-csharp Extension
            allowPrerelease: true
          settings:
            Name: ms-dotnettools.vscodeintellicode-csharp
            Ensure: Present            
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install ms-kubernetes-tools.vscode-kubernetes-tools Extension
            allowPrerelease: true
          settings:
            Name: ms-kubernetes-tools.vscode-kubernetes-tools
            Ensure: Present   
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install ria.elastic Extension
            allowPrerelease: true
          settings:
            Name: ria.elastic
            Ensure: Present   
        - resource: vscode/VSCodeExtension
          dependsOn:
            - VScode        
          directives:
            description: Install tht13.html-preview-vscode Extension
            allowPrerelease: true
          settings:
            Name: tht13.html-preview-vscode
            Ensure: Present               
